name: Sync
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: 'https://github.com/TBXark/ChatGPT-Telegram-Workers'
        source_branch: 'master'
        target_repo: 'https://github.com/xin053/ChatGPT-Telegram-Workers'
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }} 
        
